### ISSUE TITLE
Clarify attenuation semantics

### ISSUE THREAD

**Issue by clementd-fretlink** [CleverCloud/biscuit#8]
Compared to macaroons, the attenuation syntax seems to allow capabilities *extension*, whereas macaroons *structurally* guarantee that no extension can happen (by relying on boolean algebra).

The example features diff-ilke attenuation (instead of general properties the query must satisfy, attenuations are _modifications_ to the token's rule set. In isolation, each attenuation rule cannot be checked.
This implies that a reduction has to happen before the receiving service can check if the token is okay for a given request. On the contrary, macaroons verifiers check each caveat in isolation.

This leads to an important question: "who's responsible for the reduction?".
- If that's the library, it means that the attenuation semantics have to be formally expressible in a language expressive enough for describing a large range of attenuations (eg TTLs), while constrained enough to be able to prove attenuation properties on the reduction (it's not an easy feat)
- If that's the user, it means that the user has now the burden of proving that no rights expansion is possible (which is a world-class footgun, unless you force the users to issue proofs before using the library in production).

Compare this to macaroons, where we have the best of both worlds: syntax is not constrained *and* attenuation is proved by basic boolean algebra rules.

Unless biscuit ships with a rock-solid attenuation language, with structural proofs that expansion is impossible (in the current spec, this implies amongst other things computing regexes intersections),
it means that the burden of proving attenuation is transferred to the owner, which would make it a dangerous token to use.

**Comment by tarcieri** [comment]
I haven't read through the spec, but I can relay a bit of the approach I was describing which I think drove the current writeup. But perhaps I can take a step back for a bit:

From a practical perspective, I think it's important to clearly separate authority conferred upon a particular principal in an access control decision from "caveats". There is a hugely important reason to do this: user experience.

There are many ways to represent an "all caveats" construction: a set intersection, a logical disjunction (which when modus ponens is added gives you a logic for expressing third party caveats), an authorization program, but when an access control decision fails, you need to answer "why" in a way that humans can actually understand, i.e. in a prose description.

For programmers deploying these credentials, one thing is incredibly clear to me at least from the failure of Macaroons: the access control calculation needs to be abstracted away from the programmer.

Ideally I think verifying the credential involves the programmer instantiating a verification keyset and then calling a verification function which takes the credential, a set of "facts" about what is the credential bearer is proposing to do, such as a resource to be accessed and an action to be performed upon it, and potentially a big old bag of ugly ambient authority (what is their IP address, what country are they coming from, what is the authentication system's confidence score that they are on a secure terminal and have not recently been exhibiting indications of compromise).

As I've been discussing with @Geal, my personal preference for this now is authorization programs, although ones which are perhaps more in the style of Martín Abadi than Nick Szabo, and to be clear, I'm talking about server-side authorization programs here, not "smart contracts" (although if you have an access control system based on authorization programs, you can imagine embedding them in caveats and invoking them with a sort of `apply` operation).

I'm talking about languages that are roughly Prolog-ish (Abadi's Binder and Open Policy Agent are two examples). To the extent the Macaroons paper was prescriptive about a specific verification logic (most of which was not ever implemented by the OSS community), a system based on authorization programs is more flexible, and can better express intent from the practical/human side.

They are certainly capable of expressing boolean algebras, but also Prolog-like queries, and with those it's possible to write programs that can be compiled into prose or diagrams and attempt to give a reasonable explanation of the policy it's trying to express.

Concretely to do this we need to separate positive authority from restrictions/caveats, and by simply doing that, authority amplification can be avoided, and also we'll end up with an authorization decision a developer or even an end user might have a snowflake's chance in hell of comprehending (which is a diss on the incomprehensibility of past systems, not users).

To do that, instead of saying "everything is a caveat", we can look at the initial authority conferred at the time the token was minted as a set of *facts* (although in my descriptions, I have generally preferred to use the word "authority" for this set), and then describe the caveats/restrictions as a set of *rules* which are the *logical inverse* of how Macaroons restrictions would normally work (which, IMO, are incredibly redundant).

As an example, if Macaroons would have you express something like this:

- id: [1, 2, 3]
- id: [1, 3]
- id: [3]

For an authorization program example, I will use a sort of Prolog-like pseudocode, and to really screw with your brain I'm going to invert the capitalization because it drove me insane in Erlang:

### Authority ("fact" encoded in the credential)
- ID: [1,2,3]

### Rules (Caveats)
- authorized0(id) <- ?ID(id)
- authorized1(id) <- id != 2 && authorized(0)
- authorized2(id) <- id != 1 && authorized(1)

Why write things this way instead of the Macaroons way? In addition to being more expressive (a language like this is expressive enough for all of the hidden logic decisions going on in Macaroons proofs, but in a way that's written in the same language a programmer might use), as I mentioned earlier it's potentially conducive to prose or diagrammatic translations.

Here's a strawman stab at a couple examples:

```
authorized2(0)
```

"This credential is only authorized to access `id: 1, 2, 3`, but you are attempting to access `id: 0`"

```
authorized2(2)
```

"This credential cannot access `id: 2`. It was originally granted access to `id: 1, 2, 3`, but a caveat denies access to `id: 2`"

**Comment by tarcieri** [comment]
> I'd be very much in favor of reusing / building on top of existing work / specs, rather than adding the design of a new fact definition language to the scope of biscuit. 

One modern option is OpenPolicyAgent:

https://www.openpolicyagent.org/

I have various gripes with it (namely that their policy language is untyped), but it's definitely worth considering:

https://www.openpolicyagent.org/docs/language-reference.html

I would agree that creating a new language for this would be... ambitious to say the least.

**Comment by KellerFuchs** [comment]
@clementd-fretlink Did you have a look at #6 (which was merged after you openned the issue)

**Comment by divarvel** [comment]
I've only had a cursory look for now, I'll read it more carefully on
Monday, but it's close to what I had in mind.

**Comment by divarvel** [comment]
The semantics are now clearly defined, I can close this issue when the examples are updated to match what's described in #6
